contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/client.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/mod.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/types.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics03_connection/mod.rs
contracts/cosmwasm-vm/cw-ibc-core/src/lib.rs
contracts/cosmwasm-vm/cw-ibc-core/src/msg.rs
contracts/cosmwasm-vm/cw-ibc-core/src/state.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_client.rs

```bash
feat: implement get client state
```

feat: implement get client state

---

contracts/javascore/ibc/src/intTest/java/ibc/core/integration/IBCIntegrationTest.java
contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCStore.java
contracts/javascore/ibc/src/main/java/ibc/ics25/handler/IBCHandlerChannel.java
contracts/javascore/lib/src/main/java/ibc/icon/interfaces/IIBCChannelHandshake.java
contracts/javascore/lib/src/main/java/ibc/icon/interfaces/IIBCHandler.java
contracts/javascore/lib/src/main/java/ibc/icon/interfaces/IIBCHost.java
contracts/javascore/lib/src/main/java/ibc/icon/structs/messages/MsgChannelOpenTry.java
contracts/javascore/modules/mockapp/build.gradle
contracts/javascore/modules/mockapp/src/main/java/ibc/mockapp/MockApp.java
contracts/javascore/settings.gradle

Add mockApp to allow IBC handler to call relevant method hooks. Add a interface for IBC host and handler for cleaner tests.
```bash
```
```bash
```

feat: Add java integrations tests for channel establishment and closing

---

contracts/cosmwasm-vm/cw-xcall/src/admin.rs
contracts/cosmwasm-vm/cw-xcall/src/contract.rs
contracts/cosmwasm-vm/cw-xcall/src/error.rs
contracts/cosmwasm-vm/cw-xcall/src/msg.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_admin.rs

```bash
fix: enable remove, update admin and add error handling
```

fix: enable remove, update admin and add error handling

---

contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/events.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/src/msg.rs
contracts/cosmwasm-vm/cw-ibc-core/src/traits.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_client.rs

```bash
feat: implement handler for misbehaviour
```

feat: implementing handlers for misbehaviour#60

---

test/chains/cosmos/localnet.go
test/chains/cosmos/params.go
test/chains/cosmos/types.go
test/integration/admin_test.go
test/integration/executor.go
test/integration/features/admin.feature

```bash
feat(test): test script for owner can update admin list
```

feat(test): owner can update admin#46

---

.gitattributes
contracts/javascore/ibc/src/main/java/ibc/ics23/commitment/Compress.java
contracts/javascore/ibc/src/main/java/ibc/ics23/commitment/Ics23.java
contracts/javascore/ibc/src/main/java/ibc/ics23/commitment/Ops.java
contracts/javascore/ibc/src/main/java/ibc/ics23/commitment/Proof.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/BatchEntry.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/BatchProof.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/CommitmentProof.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/CompressedBatchEntry.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/CompressedBatchProof.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/CompressedExistenceProof.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/CompressedNonExistenceProof.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/ExistenceProof.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/HashOp.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/InnerOp.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/InnerSpec.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/LeafOp.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/LengthOp.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/NonExistenceProof.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/ProofSpec.java
proto/core/23-commitment/proofs.proto

feat: add proto files and generated java code for ics 23 vector commitment

---

contracts/javascore/ibc/src/intTest/java/ibc/core/integration/IBCIntegrationTest.java
contracts/javascore/ibc/src/main/java/ibc/ics25/handler/IBCHandlerChannel.java
contracts/javascore/ibc/src/main/java/ibc/ics25/handler/IBCHandlerPacket.java
contracts/javascore/ibc/src/test/java/ibc/ics25/handler/IBCHandlerTestBase.java
contracts/javascore/lib/src/main/java/ibc/icon/interfaces/IIBCModule.java
contracts/javascore/lib/src/main/java/ibc/icon/interfaces/IIBCPacket.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/BlockID.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/CanonicalBlockID.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/CanonicalVote.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/ClientState.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/Commit.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/CommitSig.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/ConsensusState.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/LightHeader.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/SignedHeader.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/SimpleValidator.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/TmHeader.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/Validator.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/ValidatorSet.java
contracts/javascore/lib/src/main/java/icon/proto/clients/tendermint/Vote.java
contracts/javascore/lib/src/main/java/icon/proto/core/channel/Channel.java
contracts/javascore/lib/src/main/java/icon/proto/core/channel/Packet.java
contracts/javascore/lib/src/main/java/icon/proto/core/connection/ConnectionEnd.java
contracts/javascore/lib/src/main/java/icon/proto/core/connection/Counterparty.java
contracts/javascore/modules/mockapp/src/main/java/ibc/mockapp/MockApp.java
contracts/javascore/proto-util/src/main/java/icon/score/proto/ProtoGen.java

Add tests for all external scenarios, testing all messages between contracts. 
Add default message in proto instead of null. 
Edit module to get channelId onChanOpenAck.
Tests are not very granular but mostly those thing that are not covered in unit tests.
```bash
```
```bash
```

feat: Add IBC java Packet integration tests

---

test/integration/features/admin.feature

```bash
test: test script for non owner cannot update admin
```

test: Add scenario for non owner updating admin

---

test/integration/features/admin.feature

```bash
test: test script for owner cannot update null value as admin
```

test: Owner cannot update admin with null value

---

contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/client.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics03_connection/delay.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics03_connection/mod.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_connection.rs

As a developer, I want to be able to initiate a connection between two blockchains using the IBC protocol, and receive confirmation that the connection has been established successfully.
And also I want to be able to configure the connection parameters, including timeouts and other security measures, to ensure that the connection is as secure and reliable as possible.
```bash
feat: implement validate connection
```

feat: 73-implement-validate-connection

---

contracts/cosmwasm-vm/cw-common/src/client_msg.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics03_connection/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/acknowledgement.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/receive_packet.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/timeout_on_close.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics24_host/host.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_host.rs

```bash
feat: implement identifier for host
```

feat: implement identifier for host#107

---

contracts/javascore/ibc/build.gradle
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/CompressedExistenceProof.java
contracts/javascore/lib/src/main/java/icon/proto/core/commitment/InnerSpec.java
contracts/javascore/proto-util/src/main/java/icon/score/proto/ProtoGen.java
contracts/javascore/score-util/src/main/java/ibc/icon/score/util/Proto.java

fix(javascore): decoding of integer array in proto generated files

---

test/chains/icon/icon_node.go
test/chains/icon/localnet.go
test/chains/icon/wallet.go
test/integration/executor.go
test/integration/features/xcall/admin.feature
test/integration/xcall_test.go

```bash
feat: generic params for executing any methods in contract
```

feat: implement params for executing methods in contract in localnet#116

---

contracts/javascore/ibc/src/main/java/ibc/ics23/commitment/Proof.java
contracts/javascore/ibc/src/test/java/ibc/ics23/commitment/LoadProofTestData.java
contracts/javascore/ibc/src/test/java/ibc/ics23/commitment/LoadVectorTestData.java
contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/TendermintLightClient.java

feat: use vector commitment methods to verify in lightclient

---

libraries/go/common/icon/icon_types_extended.go

fix: icon signed header extended method

---

.github/workflows/codecov-javascore.yml
README.md
codecov.yml
contracts/javascore/ibc/build.gradle
contracts/javascore/lightclients/tendermint/build.gradle

```bash
ci: implement codecov for javascore
```

ci: implement codecov for javascore

---

CODEOWNERS

Add @redlarva @ibrizsabin and remove @MuhammedIrfan as CODEOWNERS for cosmwasm
```bash
chore: update CODEOWNERS for cosmwasm contracts
```

chore: update CODEOWNERS for cosmwasm contracts

---

test/chains/cosmos/localnet.go
test/chains/cosmos/params.go
test/chains/icon/localnet.go
test/chains/icon/params.go
test/chains/icon/testnet.go
test/chains/types.go
test/integration/executor.go
test/integration/features/xcall/admin.feature
test/integration/xcall_test.go

```bash
test: test scripts works for icon and cosmos
```

test: if admin test scenarios for icon is working#121

---

test/chains/cosmos/cosmos_chain.go
test/chains/cosmos/testnet.go
test/chains/cosmos/types.go
test/chains/icon/localnet.go
test/chains/icon/params.go
test/chains/icon/testnet.go
test/integration/executor.go

```bash
feat: implement contract interaction in testnet for icon and cosmos
```

feat: implement execute deploy and query contract for icon testnet#118

---

contracts/cosmwasm-vm/cw-common/Cargo.toml
contracts/cosmwasm-vm/cw-common/src/lib.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/bin/schema.rs
contracts/cosmwasm-vm/cw-xcall/Cargo.toml
contracts/cosmwasm-vm/cw-xcall/src/call_message.rs
contracts/cosmwasm-vm/cw-xcall/src/contract.rs
contracts/cosmwasm-vm/cw-xcall/src/events.rs
contracts/cosmwasm-vm/cw-xcall/src/lib.rs
contracts/cosmwasm-vm/cw-xcall/src/msg.rs
contracts/cosmwasm-vm/cw-xcall/src/state.rs
contracts/cosmwasm-vm/cw-xcall/src/types/storage_keys.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_call_message.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_call_service.rs

```bash
feat: update xcall sendcall message
```

feat: update xcall sendcall message

---

contracts/cosmwasm-vm/README.md

A README file is a text file that describes and launches a project. It comprises information that is frequently needed to grasp the scope of the project
```bash
feat: update readme
```

feat: update-readme.md

---

contracts/cosmwasm-vm/cw-common/src/xcall_msg.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_execution_messages.rs
contracts/cosmwasm-vm/cw-xcall/Cargo.toml
contracts/cosmwasm-vm/cw-xcall/src/admin.rs
contracts/cosmwasm-vm/cw-xcall/src/assertion.rs
contracts/cosmwasm-vm/cw-xcall/src/call_message.rs
contracts/cosmwasm-vm/cw-xcall/src/contract.rs
contracts/cosmwasm-vm/cw-xcall/src/fee_handler.rs
contracts/cosmwasm-vm/cw-xcall/src/handle_call_message.rs
contracts/cosmwasm-vm/cw-xcall/src/lib.rs
contracts/cosmwasm-vm/cw-xcall/src/msg.rs
contracts/cosmwasm-vm/cw-xcall/src/owner.rs
contracts/cosmwasm-vm/cw-xcall/src/state.rs
contracts/cosmwasm-vm/cw-xcall/src/types/call_request.rs
contracts/cosmwasm-vm/cw-xcall/src/types/mod.rs
contracts/cosmwasm-vm/cw-xcall/src/types/request.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_admin.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_call_message.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_fee_handler.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_handle_call_message.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_ibc_functions.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_owner.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_receive_packet.rs
libraries/rust/common/src/rlp/mod.rs
libraries/rust/common/src/rlp/nullable.rs

```bash
fix: update xcall message
```

fix: update xcall message

---

.gitattributes
.github/workflows/codecov-javascore.yml
codecov.yml

chore: ignore rust proto generated files from codecov

---

contracts/cosmwasm-vm/cw-common/src/client_response.rs
contracts/cosmwasm-vm/cw-common/src/cw_types.rs
contracts/cosmwasm-vm/cw-common/src/ibc_types.rs
contracts/cosmwasm-vm/cw-common/src/lib.rs
contracts/cosmwasm-vm/cw-common/src/raw_types.rs
contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/mod.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/events.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/mod.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/acknowledgement.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/receive_packet.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/timeout.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics24_host/mod.rs
contracts/cosmwasm-vm/cw-ibc-core/src/lib.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_connection.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_execution_messages.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_port.rs
contracts/cosmwasm-vm/cw-mock-ibc-core/src/msg.rs
contracts/cosmwasm-vm/cw-xcall/src/ack.rs
contracts/cosmwasm-vm/cw-xcall/src/check.rs
contracts/cosmwasm-vm/cw-xcall/src/contract.rs
contracts/cosmwasm-vm/cw-xcall/src/handle_call_message.rs
contracts/cosmwasm-vm/cw-xcall/src/ibc.rs
contracts/cosmwasm-vm/cw-xcall/src/lib.rs
contracts/cosmwasm-vm/cw-xcall/src/state.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_call_message.rs

```bash
chore: refactor cw-ibc types
```
```bash
```

chore: refactor cw ibc types

---

test/integration/features/xcall/messaging.feature

```bash
test: test script for all execute call message scenarios 
```

test: Scenario for execute call message

---

test/integration/executor.go
test/integration/features/xcall/messaging.feature
test/integration/xcall_test.go

```bash
test: test script for all execute rollback message scenarios 
```

test: xCall Scenario for execute rollback message

---

.github/workflows/codecov-javascore.yml
.github/workflows/cosmwasm-contracts-code-coverage.yml
README.md
codecov.yml

ci: add flags on codecov report

---

contracts/javascore/lib/src/main/java/ibc/icon/interfaces/IIBCHandler.java
contracts/javascore/settings.gradle
contracts/javascore/xcall-connection/build.gradle
contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/IBCConnection.java
contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/ICallservice.java
contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/Message.java
contracts/javascore/xcall-connection/src/test/java/ibc/xcall/connection/IBCConnectionTest.java
contracts/javascore/xcall-connection/src/test/java/ibc/xcall/connection/IBCConnectionTestBase.java

Inital connection implementation, wihtout fee handling
```bash
```
```bash
```

feat: Add xcall connection to be used with multi protocol xcall

---

contracts/cosmwasm-vm/cw-common/src/constants.rs
contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
contracts/cosmwasm-vm/cw-ibc-core/src/error.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/client.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/channel.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics24_host/host.rs
contracts/cosmwasm-vm/cw-ibc-core/src/msg.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/forward_to_host.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/forward_to_xcall.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/lib.rs

feat: implemented queries for ibc core (#340)

---

contracts/javascore/ibc/src/main/java/ibc/ics03/connection/IBCConnection.java
contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCChannelHandshake.java
contracts/javascore/ibc/src/test/java/ibc/ics03/connection/ConnectionTest.java
contracts/javascore/ibc/src/test/java/ibc/ics04/channel/ChannelHandshakeTest.java

feat: Remove btpMessages on channel and connection confirm messages

---

contracts/cosmwasm-vm/cw-common/src/client_response.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_client.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_execution_messages.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/contract.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/light_client.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/traits.rs

```bash
fix: client state response
```
```bash
```

fix: client state response

---

contracts/cosmwasm-vm/cw-common/src/raw_types.rs
contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
contracts/cosmwasm-vm/cw-ibc-core/src/msg.rs

```bash
fix: query response
```
```bash
```

fix: query response

---

contracts/javascore/xcall-multi-protocol/src/main/java/foundation/icon/btp/xcall/CallServiceImpl.java
contracts/javascore/xcall-multi-protocol/src/test/java/foundation/icon/btp/xcall/CallServiceTest.java

fix: Check caller on incoming messages

---

contracts/cosmwasm-vm/cw-common/src/client_response.rs
contracts/cosmwasm-vm/cw-common/src/core_msg.rs
contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
contracts/cosmwasm-vm/cw-ibc-core/src/error.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/client.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_execution_messages.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_lightclient_integration.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/contract.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/light_client.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/state.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/traits.rs
libraries/rust/common/Cargo.toml
libraries/rust/common/src/constants.rs
libraries/rust/common/src/lib.rs
libraries/rust/common/src/traits.rs

```bash
fix: any type
```
```bash
```

fix: any type

---

contracts/javascore/ibc/src/main/java/ibc/ics05/port/ModuleManager.java
contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCHost.java
contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCStore.java
contracts/javascore/ibc/src/test/java/ibc/ics25/handler/IBCHandlerTest.java
contracts/javascore/lib/src/main/java/ibc/icon/interfaces/IIBCHost.java

feat: Change port binding to be limited to only one module

---

contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/TendermintLightClient.java

fix: Remove readonly annotation

---

.github/workflows/java-contracts-test.yml
.github/workflows/uat-deploy-java-contracts.yml
.gitignore
contracts/javascore/build.gradle
contracts/javascore/gradle.properties
contracts/javascore/ibc/build.gradle
contracts/javascore/lightclients/mockclient/build.gradle
contracts/javascore/lightclients/tendermint/build.gradle
contracts/javascore/modules/mock-dapp/build.gradle
contracts/javascore/modules/mockapp/build.gradle
contracts/javascore/xcall-connection/build.gradle
contracts/javascore/xcall-multi-protocol/build.gradle
contracts/javascore/xcall/build.gradle

* integrate UAT environment running on aws instance to test contract deployment
```bash
```
```bash
```

ci: create separate workflow for contract deployment on UAT environment

---

docs/adr/multi-protocol-xcall.md

docs: Add initial draft of xCall multi protocol specification

---

docs/adr/XCall_IBC_Connection.md

Add docment describing the design of a xCall connection using IBC.
```bash
```
```bash
```

docs: Final draft xCall IBC connection

---

contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
contracts/javascore/ibc/src/test/java/ibc/ics04/channel/PacketTest.java

feat: Change packet hashing from sha256 to keccak256

---

.github/workflows/uat-deploy-java-contracts.yml

fix: deployment to uat for java contracts

---

contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
contracts/javascore/ibc/src/main/java/ibc/ics23/commitment/types/Merkle.java
contracts/javascore/ibc/src/test/java/ibc/ics04/channel/PacketTest.java
contracts/javascore/score-util/src/main/java/ibc/icon/score/util/StringUtil.java

fix: remove decodeurl and fix double hashing in recvPacket.

---

contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCHost.java
contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCStore.java
contracts/javascore/ibc/src/main/java/ibc/ics25/handler/IBCHandler.java
contracts/javascore/ibc/src/test/java/ibc/ics02/client/ClientTest.java
contracts/javascore/ibc/src/test/java/ibc/ics25/handler/IBCHandlerTest.java

fix: Port Ids to string

---

Cargo.lock
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/handler/open_init.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_channel_closeinit.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_close_confirm.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_execution_channel.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_handler.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_open_ack.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_open_confirm.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_host.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_storage.rs
contracts/cosmwasm-vm/cw-integration/tests/test_xcall_connection.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_ibc_functions.rs
contracts/cosmwasm-vm/cw-xcall/src/contract.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_ibc_functions.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_receive_packet.rs
libraries/rust/common/src/ibc/core/ics04_channel/channel.rs

fix: type conversion to cosmwasm_std order

---

contracts/cosmwasm-vm/cw-common/src/commitment.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/channel.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/events.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/handler/close_confirm.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/handler/open_try.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/receive_packet.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/timeout.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_receive_packet.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_channel.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/contract.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_ibc_functions.rs
contracts/cosmwasm-vm/cw-xcall/src/ibc.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_ibc_functions.rs
libraries/rust/common/src/ibc/core/ics04_channel/channel.rs

```bash
feat: unordered channel
```
```bash
```

feat: unordered channel

---

contracts/cosmwasm-vm/cw-common/src/client_msg.rs
contracts/cosmwasm-vm/cw-common/src/core_msg.rs
contracts/cosmwasm-vm/cw-common/src/xcall_msg.rs
contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/channel.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/timeout.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_timeout.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_channel.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/contract.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/light_client.rs
contracts/cosmwasm-vm/cw-integration/src/lib.rs
contracts/cosmwasm-vm/cw-integration/tests/setup.rs
contracts/cosmwasm-vm/cw-integration/tests/test_host_lightclient.rs
contracts/cosmwasm-vm/cw-mock-dapp/src/contract.rs
contracts/cosmwasm-vm/cw-xcall/src/call_message.rs
contracts/cosmwasm-vm/cw-xcall/src/contract.rs
contracts/cosmwasm-vm/cw-xcall/tests/test_call_message.rs

```bash
feat: handle for packet timeout.
```
```bash
```

feat: handle for packet timeout

---

contracts/javascore/ibc/src/intTest/java/ibc/core/integration/IBCIntegrationTest.java
contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCStore.java
contracts/javascore/ibc/src/main/java/ibc/ics25/handler/IBCHandlerPacket.java
contracts/javascore/ibc/src/test/java/ibc/ics04/channel/PacketTest.java
contracts/javascore/ibc/src/test/java/ibc/ics25/handler/IBCHandlerTest.java
contracts/javascore/ibc/src/test/java/ibc/ics25/handler/IBCHandlerTestBase.java
contracts/javascore/lib/src/main/java/ibc/icon/interfaces/IIBCPacket.java
contracts/javascore/lib/src/main/java/ibc/icon/structs/messages/MsgRequestTimeoutPacket.java

fix: request timeout

---

contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/events.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/timeout.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_channel.rs

fix: timeout packet event

---

contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/events.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/acknowledgement.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/timeout.rs

```bash
fix: archway eventlogs for channels
```
```bash
```

fix: archway channel event

---

libraries/rust/common/src/ibc/core/ics03_connection/connection.rs
libraries/rust/common/src/ibc/core/ics23_commitment/commitment.rs

chore: handle merkle prefix empty on javascore

---

optimize_build.sh

chore: check size of wasm files

---

contracts/cosmwasm-vm/cw-ibc-core/src/context.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/handler/close_confirm.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/handler/open_ack.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/handler/open_confirm.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/handler/open_try.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/acknowledgement.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/receive_packet.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/timeout.rs
contracts/cosmwasm-vm/cw-ibc-core/src/state.rs
contracts/cosmwasm-vm/cw-ibc-core/src/storage_keys.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_acknowledgement.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_channel_closeinit.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_close_confirm.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_execution_channel.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_open_ack.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_open_confirm.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_receive_packet.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_timeout.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_channel.rs
contracts/cosmwasm-vm/cw-integration/tests/test_host_lightclient.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs

```bash
fix: remove callback data
```
```bash
```

fix: remove callback data

---

.github/workflows/basic-rust.yml
.github/workflows/cosmwasm-contracts-code-coverage.yml
.github/workflows/deploy-cosmwasm-contracts.yml
libraries/rust/common/src/btp_header.rs

```bash
fix: empty message root encoding
```
```bash
```

fix: empty message root encoding

---

.github/workflows/deploy-cosmwasm-contracts.yml
contracts/cosmwasm-vm/cw-common/src/xcall_app_msg.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/lib.rs
contracts/cosmwasm-vm/cw-xcall-multi/src/connection.rs
contracts/cosmwasm-vm/cw-xcall-multi/src/contract.rs
contracts/cosmwasm-vm/cw-xcall-multi/src/lib.rs
contracts/cosmwasm-vm/cw-xcall-multi/src/msg.rs
scripts/deploy_cosmwasm.sh

fix: xcall multi add default connection

---

contracts/cosmwasm-vm/cw-ibc-core/src/ics03_connection/handler.rs

fix: connection open confirm eventlog issue fix

---

Makefile
scripts/.DockerfileContractBuilder
scripts/optimize-build.sh
scripts/optimize-cosmwasm.sh

feat:  added build script for both cosmwasm and icon using docker

---

test/chains/cosmos/localnet.go
test/chains/icon/localnet.go
test/relayer/icon/icon_relayer.go

fix: e2e testing for non adjacent update

---

test/chains/cosmos/localnet.go
test/chains/icon/localnet.go
test/e2e/e2e-config.yaml
test/e2e/testsuite/testsuite.go
test/relayer/config.go
test/relayer/icon/icon_relayer.go

fix: relay config issue after update

---

test/chains/cosmos/localnet.go

fix: e2e cosmos findevent not found

---

go.mod
test/chains/chain.go
test/chains/chainConfig.go
test/chains/cosmos/cosmos_chain.go
test/chains/cosmos/localnet.go
test/chains/icon/icon_chain.go
test/chains/icon/localnet.go
test/chains/types.go
test/e2e/e2e-config-neutron.yaml
test/e2e/tests/xcall.go
test/e2e/testsuite/testsuite.go

feat: e2e setup for neutron

---

contracts/cosmwasm-vm/cw-common/src/core_msg.rs
contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
contracts/cosmwasm-vm/cw-ibc-core/src/light_client/light_client.rs

feat: add client consensus query method by height

---

README.md

docs: add badges-status,license

---

Cargo.toml
contracts/cosmwasm-vm/cw-common/Cargo.toml
contracts/cosmwasm-vm/cw-ibc-core/Cargo.toml
contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
contracts/cosmwasm-vm/cw-ibc-core/src/lib.rs
contracts/cosmwasm-vm/cw-icon-light-client/Cargo.toml
contracts/cosmwasm-vm/cw-icon-light-client/src/contract.rs
contracts/cosmwasm-vm/cw-integration/Cargo.toml
contracts/cosmwasm-vm/cw-mock-ibc-core/Cargo.toml
contracts/cosmwasm-vm/cw-xcall-ibc-connection/Cargo.toml
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/lib.rs
test/chains/cosmos/localnet.go

```bash
feat: add version logging on migration
```
```bash
Log contract version on migration.
Read package version from workspace cargo.toml
```

feat: add version logging on migration

---

Cargo.lock
contracts/cosmwasm-vm/cw-ibc-core/src/light_client/light_client.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/.cargo/config
contracts/cosmwasm-vm/cw-mock-ibc-dapp/Cargo.toml
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/admin.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/assertion.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/check.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/contract.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/error.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/ibc.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/ibc_host.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/lib.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/msg.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/owner.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/receive_packet.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/send_message.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/state.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/types/config.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/types/dapp_msg.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/types/message.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/types/mod.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/types/storage_keys.rs

```bash
feat: mock ibc dapp
```
```bash
-  Added mock dapp which implement ibc module interface for testing
-  Fixed typo.
```

feat: mock ibc dapp

---

Cargo.lock
contracts/cosmwasm-vm/cw-common/Cargo.toml
contracts/cosmwasm-vm/cw-common/src/lib.rs
contracts/cosmwasm-vm/cw-common/src/utils.rs
contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics03_connection/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/handler.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/acknowledgement.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/receive_packet.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/send_packet.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/timeout_on_close.rs
contracts/cosmwasm-vm/cw-ibc-core/src/state.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/contract.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/light_client.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/query_handler.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/state.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/traits.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/ibc.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/ibc_host.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/receive_packet.rs

```bash
feat: add debug print
```
```bash
- macro to export debug logs to chains environment so that we can extract the logs.
```

feat: add debug print

---

README.md

Add the status of test for java smart contracts and cosmwasm smart contracts
```bash
docs: add rest badges for java and rust
```
```bash
```

docs: add test badges for java and rust

---

CODEOWNERS

feat: updated code owner lists

---

contracts/cosmwasm-vm/README.md
contracts/javascore/README.md

```bash
docs: add docs for java smart contracts
```
```bash
```

docs: add docs for java smart contracts

---

.github/workflows/cosmwasm-contracts-code-coverage.yml

ci: add cw-xcall-ibc-connection to Codecov

---

README.md

update typo in table of content
```bash
docs:  Update README - fix typo
```
```bash
```

docs:  Update README - fix typo

---

README.md

fix: change readme xCall link

---

contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/acknowledgement.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/receive_packet.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/timeout.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/timeout_on_close.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/contract.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/contract.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/lib.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/send_message.rs
contracts/cosmwasm-vm/cw-mock-ibc-dapp/src/state.rs

Add address validation checks on main code where we are using Addr::unchecked or not performing addr validation.
```bash
fix: add addr validation
```
```bash
0.1.0 : Add address validation
```

fix: missing cosmwasm address validation. #192

---

contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/receive_packet.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_execution_channel.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_receive_packet.rs

```bash
fix: recv packet complexity #189
```
```bash
0.1.0: Removed logic from receive reply.
```

fix: Recv Packet complexity #189

---

contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/IBCConnection.java

fix: todo comments removed

---

contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/IBCConnection.java

fix: requiring couterpartyNid to be valid

---

contracts/javascore/ibc/src/main/java/ibc/ics03/connection/IBCConnection.java
contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
contracts/javascore/ibc/src/main/java/ibc/ics05/port/ModuleManager.java
contracts/javascore/ibc/src/main/java/ibc/ics23/commitment/types/Merkle.java
contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCHost.java
contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCStore.java
contracts/javascore/lib/src/main/java/ibc/icon/interfaces/ILightClient.java
contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/TendermintLightClient.java
contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/Verifier.java
contracts/javascore/score-util/src/main/java/ibc/icon/score/util/ByteUtil.java
contracts/javascore/test-lib/src/main/java/ibc/icon/integration/Env.java

fix: Remove unused code and imports in Java score

---

contracts/javascore/ibc/src/main/java/ibc/ics23/commitment/types/Merkle.java
contracts/javascore/ibc/src/test/java/ibc/ics23/commitment/types/MerkleTest.java
contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/TendermintLightClient.java

fix: Optimze fetching SDK spec during ICS-23 merkle proofs

---

contracts/cosmwasm-vm/cw-icon-light-client/src/light_client.rs

```bash
fix: single validator can sign a block more than one time. #188
```
```bash
0.1.0: Prevent duplicate signatures from generating votes.
```

fix: duplicate signatures issue

---

contracts/javascore/ibc/src/main/java/ibc/ics25/handler/IBCHandler.java

fix: owner check removed from ibc-handler

---

contracts/javascore/ibc/src/main/java/ibc/ics03/connection/IBCConnection.java
contracts/javascore/ibc/src/main/java/ibc/ics23/commitment/Compress.java
contracts/javascore/ibc/src/main/java/ibc/ics23/commitment/Proof.java
contracts/javascore/ibc/src/main/java/ibc/ics23/commitment/types/Merkle.java

fix: Optimize use of size() == 0 to isEmpty in javascore

---

contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/IBCConnection.java
contracts/javascore/xcall-connection/src/test/java/ibc/xcall/connection/IBCConnectionTest.java

fix: Amend Java xCall connection planted issues

---

.github/labeler.yml
.github/workflows/auto-pr-labeler.yaml
.github/workflows/check-pr-label.yaml

* auto add default label
```bash
```
```bash
```

ci: add pr label checker

---

contracts/javascore/xcall-connection/build.gradle
contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/IBCConnection.java
test/chains/icon/localnet.go

fix: port initialization removed

---

contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCChannelHandshake.java

fix: if connection open check is added

---

contracts/javascore/ibc/src/intTest/java/ibc/core/integration/IBCIntegrationTest.java
contracts/javascore/ibc/src/main/java/ibc/ics02/client/IBCClient.java
contracts/javascore/ibc/src/main/java/ibc/ics03/connection/IBCConnection.java
contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCChannelHandshake.java
contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
contracts/javascore/ibc/src/main/java/ibc/ics25/handler/IBCHandlerChannel.java
contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/TendermintLightClient.java

Remove fixed or non needed todos
Remove commented code
Remove bad comments
```bash
```
```bash
```

fix: Cleanup comments and TODOs in IBC Java score

---

contracts/cosmwasm-vm/cw-common/src/xcall_connection_msg.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/config_response.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/mod.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_ibc_functions.rs
contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/IBCConnection.java
contracts/javascore/xcall-connection/src/test/java/ibc/xcall/connection/IBCConnectionTest.java

feat: Add method to get IBC config for xCall connections

---

contracts/cosmwasm-vm/cw-common/src/xcall_connection_msg.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/config_response.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/mod.rs

fix: setFees is admin guarded

---

.github/workflows/deploy-cosmwasm-contracts.yml
.gitmodules
Cargo.toml
scripts/archway/docker_compose_archway.yaml
scripts/archway/localnet.sh
scripts/deploy_cosmwasm.sh
scripts/optimize-cosmwasm.sh

ci: fix cosmwasm contract deployment

---

contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCStore.java
contracts/javascore/lib/src/main/java/ibc/icon/interfaces/IIBCHost.java
test/chains/icon/params.go

fix: hasPacketReciept method removed

---

contracts/cosmwasm-vm/cw-common/src/xcall_connection_msg.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/config_response.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/mod.rs

```bash
fix: admin guard added on close channel
```
```bash
```

fix: admin guard added on close channel

---

contracts/cosmwasm-vm/cw-common/src/xcall_connection_msg.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/config_response.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/mod.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_ibc_functions.rs

```bash
fix: static version check removed
```
```bash
```

fix: static version check removed

---

contracts/cosmwasm-vm/cw-common/src/xcall_connection_msg.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/send_message.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/config_response.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/mod.rs

```bash
fix: xcall check commented out 
```
```bash
```

fix: xcall check commented out

---

.gitmodules
contracts/javascore/settings.gradle
contracts/javascore/xcall-connection/build.gradle
scripts/build-xcall.sh
scripts/clean-build-and-exexute-e2e.sh
scripts/optimize-cosmwasm.sh
scripts/optimize-jar.sh
test/chains/chain.go
test/chains/cosmos/localnet.go
test/chains/cosmos/params.go
test/chains/cosmos/types.go
test/chains/icon/localnet.go
test/chains/icon/params.go
test/chains/methods.go
test/e2e/tests/xcall.go
test/integration/tests/relayer.go
test/testsuite/sample-config-archway.yaml
test/testsuite/sample-config-neutron.yaml

```bash
fix: e2e and integration test cleanup
```
```bash
```

fix: e2e and integration test cleanup

---

contracts/cosmwasm-vm/cw-icon-light-client/src/contract.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/error.rs
contracts/cosmwasm-vm/cw-icon-light-client/src/light_client.rs

```bash
fix: disallow duplicate update header for same height
```
```bash
```

fix: disallow duplicate update header for same height

---

scripts/deploy_cosmwasm.sh

chore: exclude cosmwasm library and common file from contract deployment

---

contracts/cosmwasm-vm/cw-mock-ibc-connection/src/admin.rs

```bash
fix: owner check removed in addAdmin
```
```bash
```

fix: owner check removed in addAdmin

---

.github/workflows/deploy-cosmwasm-contracts.yml
scripts/deploy_cosmwasm.sh
test/integration/tests/relayer.go
test/testsuite/integration_suite.go

```bash
feat: test multiple packets on same height
```
```bash
```

feat: test multiple packets on same height

---

contracts/cosmwasm-vm/cw-common/src/core_msg.rs
contracts/cosmwasm-vm/cw-ibc-core/src/context.rs
contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/write_acknowledgement.rs
contracts/cosmwasm-vm/cw-ibc-core/src/state.rs
contracts/cosmwasm-vm/cw-ibc-core/src/storage_keys.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_write_acknowledgement.rs

```bash
feat: add write ack log
```
```bash
```

feat: add write ack log

---

.gitignore
Cargo.lock
Cargo.toml
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/xcall.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_ibc_functions.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_receive_packet.rs
scripts/optimize-xcall-build.sh

```bash
fix: point to xcall tag
```
```bash
```

fix: point to xcall tag

---

contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/IBCConnection.java
contracts/javascore/xcall-connection/src/test/java/ibc/xcall/connection/IBCConnectionTest.java

```bash
fix: address decoding on fee claim
```
```bash
```

fix: address decoding on fee claim

---

.github/workflows/release.yaml
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/ibc_host.rs
contracts/javascore/build.gradle
scripts/optimize-cosmwasm.sh

```bash
```
```bash
```
- [] I only have one commit (if not, squash them into one commit).

feat: Add artifact checksum in release

---

.github/workflows/release.yaml

ci: fix download error

---

.github/workflows/release.yaml

ci: revert release workflow changes

---

.github/deployer/init_script.sh

```bash
ci: make secret files inaccessable to other users
```
```bash
```

ci: make secret files inaccessable to other users

---

.github/workflows/release.yaml

```bash
ci: update release build tag format 
```
```bash
```

ci: update release build tag format

---

contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/TendermintLightClient.java
contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/LightClientTestBase.java

```bash
hotfix: neutron client 
```
```bash
```

fix: tests

---

contracts/javascore/lightclients/tendermint/build.gradle
contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/TendermintLightClient.java
contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/LightClientTestBase.java

```bash
fix: neutron client update
```
```bash
```

fix: neutron client update

---

.github/workflows/check-pr-label.yaml

ci: add dependency between workflows, and add more label in the list

---

contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/TendermintHelper.java
contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/TendermintLightClient.java
contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/LightClientTest.java
contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/LightClientTestBase.java

Add revision number but for now do not add support for resseting chain height
```bash
```
```bash
```

feat: Add revision number to light client heights

---

libraries/go/common/tendermint/consensus_state_extended.go

```bash
feat: implement get timestamp for tendermint
```
```bash
```

feat: implement get timestamp for tendermint

---

docs/e2e-integration-test-setup.md

```bash
fix: added clarity and fixed bash commands to work effortlessly
```
```bash
```

fix: added clarity and fixed bash commands to work effortlessly

---

contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
contracts/javascore/ibc/src/test/java/ibc/ics04/channel/PacketTest.java

fix: Fix reverse sign on timestamp check for request timeout

---

contracts/cosmwasm-vm/cw-ibc-core/tests/setup.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_client.rs

Improve test cases for ics-02 client
- updated existing test cases
- added new test cases to cover edge cases

chore: update test coverage for ibc client

---

contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_acknowledgement.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_channel_closeinit.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_close_confirm.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_handler.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_open_ack.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_open_confirm.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_packet.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_receive_packet.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_timeout.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_timeout_on_close.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_channel.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_connection.rs
contracts/cosmwasm-vm/cw-ibc-core/tests/test_host.rs

changes made
- update existing test coverage
- add additional test coverage for host, connection and channel

chore: add test coverage for cosmwasm ibc core

---

contracts/javascore/ics20/build.gradle
contracts/javascore/ics20/src/main/java/ibc/ics20/ICS20Transfer.java
contracts/javascore/ics20/src/test/java/ibc/ics20/ICS20TransferTest.java
contracts/javascore/lib/src/main/java/ics20/ICS20Lib.java
contracts/javascore/score-util/src/main/java/ibc/icon/score/util/StringUtil.java
contracts/javascore/settings.gradle

```bash
feat: add ics20-irc2 support
```
```bash
```

feat: add ics20-irc2 support

---

contracts/javascore/ics20/src/main/java/ibc/ics20/ICS20Transfer.java

fix: acknowledgement compare issue fixed

---

contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/assertion.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/fee.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/setup.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_admin.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_call_service.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_ibc.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_ibc_functions.rs
contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_owner.rs

changes made
- add test coverage for xcall-ibc-connection

chore: add test coverage for xcall-ibc-connection

---

.github/deployer/init_script.sh

ci: migrate deployment script

---

.github/workflows/deploy-cosmwasm-contracts.yml
.github/workflows/release.yaml

ci: update rust version from 1.69.0 to 1.78.0

---

.github/deployer/init_script.sh

ci: update devnet repo url

---

.github/deployer/init_script.sh
.github/workflows/run-deployer.yml

872 update repo url in deployment script

---

.github/deployer/ec2_deployer.tf
.github/deployer/init_script.sh

ci: add solana binary installation and update sudoer path

---

.github/deployer/sui_import.sh

```bash
fix: wallet update sui_import.sh
```
```bash
```

fix: wallet update sui_import.sh

---

.github/deployer/init_script.sh

```bash
fix: solana install script update
```
```bash
```

fix: solana install script update
