- test/integration/admin_test.go
- test/integration/executor.go
- test/integration/features/admin.feature
```bash
test: test script for owner cannot set admin twice
```
> test: owner cannot set admin twice#53

- contracts/cosmwasm-vm/cw-ibc-core/tests/test_connection.rs
As a developer, I want the "get_connection" query handler to be able to retrieve and share basic information about the connection, such as its ID, state, and associated counterparty.
```bash
feat: implement query get connection
```
> feat: 72-implementing-query-get-connection

- contracts/cosmwasm-vm/cw-xcall/src/admin.rs
- contracts/cosmwasm-vm/cw-xcall/src/contract.rs
- contracts/cosmwasm-vm/cw-xcall/src/error.rs
- contracts/cosmwasm-vm/cw-xcall/src/types/address.rs
- contracts/cosmwasm-vm/cw-xcall/tests/test_admin.rs
```bash
fix: handle panic and return error and Update add admin with address validation
```
> fix: 84 bugxcall contract panics when we query get admin when list is empty

- contracts/cosmwasm-vm/cw-xcall/src/admin.rs
- contracts/cosmwasm-vm/cw-xcall/src/contract.rs
- contracts/cosmwasm-vm/cw-xcall/src/lib.rs
- contracts/cosmwasm-vm/cw-xcall/src/types/address.rs
- contracts/cosmwasm-vm/cw-xcall/tests/test_admin.rs
```bash
fix: invalid chars cannot be added as the admin address
```
> fix: invalid chars cannot be added as admin address

- contracts/cosmwasm-vm/cw-ibc-core/src/ics05_port/port.rs
- contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_receive_packet.rs
- contracts/cosmwasm-vm/cw-ibc-core/tests/test_port.rs
As a developer, I want to be able to query the module by channel to retrieve the module address from the store, 
```bash
feat: impelement lookup module by channel
```
> feat: implement lookup module by channel

- contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
- contracts/javascore/ibc/src/test/java/ibc/ics04/channel/PacketTest.java
During implementation the wrong packet commitment format was used.
References:
https://github.com/cosmos/ibc-go/blob/fa10438afcbd77262148dfd9cfbbe76e6d45d873/modules/core/04-channel/types/packet.go#L19
https://github.com/cosmos/ibc/blob/main/spec/core/ics-004-channel-and-packet-semantics/README.md
```bash
```
```bash
```
> fix: hash packet data before creating packet commitment

- contracts/javascore/ibc/src/main/java/ibc/ics02/client/IBCClient.java
- contracts/javascore/ibc/src/main/java/ibc/ics03/connection/IBCConnection.java
- contracts/javascore/ibc/src/test/java/ibc/ics02/client/ClientTest.java
- contracts/javascore/ibc/src/test/java/ibc/ics03/connection/ConnectionTest.java
- contracts/javascore/ibc/src/test/java/ibc/ics25/handler/IBCHandlerTestBase.java
Since we can't do multi height proofs in a simple way we need to provide relevant data needed by counter party for every connection update.
Client state and consensus states should only be needed to verify during connection establishment and not required after.
```bash
```
```bash
```
> feat: Only send client and consensus state when updating a connection

- contracts/javascore/ibc/src/main/java/ibc/ics02/client/IBCClient.java
- contracts/javascore/ibc/src/main/java/ibc/ics03/connection/IBCConnection.java
- contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
- contracts/javascore/ibc/src/test/java/ibc/ics02/client/ClientTest.java
- contracts/javascore/ibc/src/test/java/ibc/ics03/connection/ConnectionTest.java
- contracts/javascore/ibc/src/test/java/ibc/ics04/channel/PacketTest.java
- contracts/javascore/ibc/src/test/java/ibc/ics25/handler/IBCHandlerTest.java
- contracts/javascore/ibc/src/test/java/ibc/ics25/handler/IBCHandlerTestBase.java
- contracts/javascore/modules/mockapp/src/main/java/ibc/mockapp/MockApp.java
All packets sent from a counterparty using the ICON lightclient wont be able to use timestamps. So in order to be able to timeout we should require timeout height to be set and timeout timestamp to be zero.
```bash
```
```bash
```
> feat: Require 0 timeout timestamp for outgoing packets

- contracts/cosmwasm-vm/cw-ibc-core/src/ics05_port/mod.rs
- contracts/cosmwasm-vm/cw-ibc-core/src/ics05_port/port.rs
- contracts/cosmwasm-vm/cw-ibc-core/tests/test_host.rs
- contracts/cosmwasm-vm/cw-ibc-core/tests/test_port.rs
As a developer, I want to implement the "bindport" functionality for the "port" module, so that I can allow clients to bind to a particular port and establish a connection with a corresponding port on another chain.
```bash
feat: implement bindport
```
> feat: implement bindport

- contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCHost.java
- contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCStore.java
portIds stores all the keys for the capabilities db. Each time a unique key is found, it's added in the portid database. Uniqueness is determined if capabilities hash 0 address for that key. There doesn't seem to be method to remove capability, thus it's assumed that the address size for any key will not be reduced to zero which may hamper the uniqueness assumption.
```bash
```
```bash
```
> feat: add getBindPorts method

- contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
- contracts/javascore/ibc/src/test/java/ibc/ics04/channel/PacketTest.java
Remove double hashing as requested by relay team
```bash
```
```bash
```
> feat: remove double hashing, use sha256 only

- contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
- contracts/javascore/ibc/src/test/java/ibc/ics04/channel/PacketTest.java
- contracts/javascore/score-util/src/main/java/ibc/icon/score/util/Proto.java
In IBC handler all biginteger numbers are converted to 64 bit fixed length bytes. For proto it didn't like BigInteger.ZERO being converted to 64 bit. Tests were failing in tendermint light client. Thus only IBC handler sends 0 as 64 bit bytes.
```bash
```
```bash
```
> feat: convert BigInteger numbers to fixed 64 length bytes

- contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
- contracts/javascore/ibc/src/test/java/ibc/ics04/channel/PacketTest.java
- contracts/javascore/score-util/src/main/java/ibc/icon/score/util/Proto.java
- contracts/javascore/score-util/src/test/java/ibc/icon/score/util/ProtoTest.java
Allow option to choose between little endian and big endian encoding
```bash
```
```bash
```
> feat: allow option to choose between little endian and big endian encoding

- contracts/cosmwasm-vm/cw-ibc-core/tests/test_connection.rs
As a developer , I want to implement a port capability path so that I can easily establish connections and transfer data between different modules. I want to be able to create a port capability for my module, so that other modules can establish connections with my module and initiate data transfer. And also want to establish a connection with another module by providing its port capability path, so that I can initiate data transfer between the two modules.
```bash
feat: implement port capability
```
> feat: implement-port-capability-path

- contracts/javascore/ibc/src/intTest/java/ibc/core/integration/IBCIntegrationTest.java
- contracts/javascore/ibc/src/main/java/ibc/ics02/client/IBCClient.java
- contracts/javascore/ibc/src/test/java/ibc/ics02/client/ClientTest.java
- contracts/javascore/ibc/src/test/java/ibc/ics25/handler/IBCHandlerTestBase.java
- contracts/javascore/lib/src/main/java/ibc/icon/interfaces/ILightClient.java
- contracts/javascore/lib/src/main/java/ibc/icon/structs/messages/MsgCreateClient.java
- contracts/javascore/lightclients/mockclient/src/main/java/ibc/mockclient/MockClient.java
- contracts/javascore/lightclients/tendermint/build.gradle
- contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/TendermintLightClient.java
- contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/LightClientTestBase.java
- contracts/javascore/xcall/src/intTest/java/ibc/xcall/integration/XCallIntegrationTest.java
To allow contract specific prefix for the lightclients we introduce a new client specific variable that is prefixed to the path before doing membership or non membership proofs
```bash
```
```bash
```
> feat: Add storage prefix argument to create client

- .gitignore
- test/chains/cosmos/localnet.go
- test/chains/icon/localnet.go
- test/e2e/config.yaml
Implement xCall abstractions for cosmwasm chains, xCall is not currently working so details about implementation might change once it is completed
```bash
```
```bash
```
> feat: Implememt xCall abstraction for archway in E2E test

- contracts/javascore/ibc/src/main/java/ibc/ics03/connection/IBCConnection.java
- contracts/javascore/ibc/src/test/java/ibc/ics03/connection/ConnectionTest.java
- contracts/javascore/ibc/src/test/java/ibc/ics04/channel/ChannelHandshakeTest.java
- contracts/javascore/ibc/src/test/java/ibc/ics04/channel/PacketTest.java
- contracts/javascore/score-util/src/main/java/ibc/icon/score/util/Proto.java
Remove java commitment prefix and fix issue when ecoding nested proto messages
```bash
```
```bash
```
> feat: Remove commitment prefix

- contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCStore.java
- contracts/javascore/lib/src/main/java/ibc/icon/interfaces/IIBCHost.java
- contracts/javascore/modules/mock-dapp-multi-protocol/src/main/java/ibc/xcall/sample/dapp/MultiProtocolSampleDapp.java
- contracts/javascore/xcall-connection/build.gradle
- contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/IBCConnection.java
- contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/ICallservice.java
- contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/Message.java
- contracts/javascore/xcall-connection/src/test/java/ibc/xcall/connection/IBCConnectionTest.java
- contracts/javascore/xcall-connection/src/test/java/ibc/xcall/connection/IBCConnectionTestBase.java
- contracts/javascore/xcall-multi-protocol/src/main/java/foundation/icon/btp/xcall/CSMessageRequest.java
- contracts/javascore/xcall-multi-protocol/src/main/java/foundation/icon/btp/xcall/CSMessageResponse.java
- contracts/javascore/xcall-multi-protocol/src/main/java/foundation/icon/btp/xcall/CallRequest.java
- contracts/javascore/xcall-multi-protocol/src/main/java/foundation/icon/btp/xcall/CallService.java
- contracts/javascore/xcall-multi-protocol/src/main/java/foundation/icon/btp/xcall/CallServiceImpl.java
- contracts/javascore/xcall-multi-protocol/src/main/java/foundation/icon/btp/xcall/DefaultCallServiceReceiver.java
- contracts/javascore/xcall-multi-protocol/src/main/java/foundation/icon/btp/xcall/FeeManage.java
- contracts/javascore/xcall-multi-protocol/src/test/java/foundation/icon/btp/xcall/CallServiceTest.java
- docs/adr/XCall_IBC_Connection.md
- docs/adr/multi-protocol-xcall.md
Add fee logic to connection, allow xCall to be used the same as original xCall by introducing optional parameters and admin controlled default protocols. Use per connection timeout height based on each lightclient.
```bash
```
```bash
```
> feat: Update xCall and IBC connection to lates spec and update spec

- Cargo.lock
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/receive_packet.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/send_message.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/state.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/xcall.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_ibc_functions.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_receive_packet.rs
- contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/IBCConnection.java
- contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/ICallservice.java
- contracts/javascore/xcall-connection/src/test/java/ibc/xcall/connection/IBCConnectionTest.java
- test/chains/chain.go
- test/chains/cosmos/localnet.go
- test/chains/icon/localnet.go
- test/e2e/tests/xcall.go
> feat: Adapt connection to xCall optimizations

- contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCStore.java
- contracts/javascore/ibc/src/test/java/ibc/ics04/channel/PacketTest.java
- contracts/javascore/lib/src/main/java/ibc/icon/interfaces/IIBCHost.java
> fix: Use string keys for return map in getPacketHeights

- .github/workflows/uat-deploy-java-contracts.yml
Currently the submodules are not cloned while running the deployment to uat ci. With this change, the submodules are also cloned to fix the error currently CI is having.
```bash
feat: clone submodules to deploy java smart contracts
```
```bash
```
> feat: clone submodules to deploy java smart contracts

- contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
- contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCCommitment.java
> fix: Use built in Arrays.equals instead of our own version

- contracts/javascore/ibc/src/main/java/ibc/ics03/connection/IBCConnection.java
- contracts/javascore/ibc/src/test/java/ibc/ics03/connection/ConnectionTest.java
> fix: Only allow connection to be in INIT state during connectionOpenAck

- contracts/javascore/lightclients/mockclient/src/main/java/ibc/mockclient/MockClient.java
- contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/TendermintLightClient.java
> fix: Make verify membership functions readonly in tendermint lightclient

- docs/adr/XCall_IBC_Connection.md
> fix: Update xcall connection spec to match implementation

- .gitignore
- contracts/cosmwasm-vm/cw-common/src/client_msg.rs
- contracts/cosmwasm-vm/cw-common/src/core_msg.rs
- contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
- contracts/cosmwasm-vm/cw-ibc-core/src/light_client/light_client.rs
- contracts/cosmwasm-vm/cw-icon-light-client/src/contract.rs
A method to return prev consensus height with respect to provided height was added in ibc-core. 
```bash
fix: icon client add prev consensus height method.
```
```bash
```
> fix: icon client add prev consensus height method

- .github/workflows/release_tag_manager.yml
> ci: add manual trigger cicd job to create and push release tag

- contracts/cosmwasm-vm/cw-common/src/xcall_connection_msg.rs
- contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/timeout.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/config_response.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/mod.rs
```bash
fix: send packet height is not set to zero during timeout packet 
```
```bash
0.1.0: Set height zero when packet times out
```
> fix: send packet height is not set to zero during timeout packet

- contracts/javascore/settings.gradle
- scripts/optimize-cosmwasm.sh
* fix cosmwasm-check binary install issue using --locked in cargo install
* update xCall name
```bash
```
```bash
```
> ci: fix build issues

- contracts/cosmwasm-vm/cw-common/src/xcall_connection_msg.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/config_response.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/mod.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_ibc_functions.rs
- contracts/javascore/xcall-connection/src/main/java/ibc/xcall/connection/IBCConnection.java
```bash
fix: additional checks added in configure connection 
```
```bash
```
> fix: additional checks added in configure connection

- contracts/cosmwasm-vm/cw-common/src/xcall_connection_msg.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/admin.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/config_response.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/types/mod.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_admin.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_ibc_functions.rs
```bash
fix: permissions on xcall connection
```
```bash
```
> fix: permissions on xcall connection

- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/lib.rs
The instantiate entry point is not marked as library
```bash
feat: add library feature for xcall ibc connection
```
```bash
```
> feat: add library feature for xcall ibc connection

- contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
IBC query method get consensus state by height should return any type consensus state 
```bash
fix: ibc query method get consensus state by height should return a…
```
```bash
```
> fix: ibc query method get consensus state by height should return any type

- contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
- contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCStore.java
- contracts/javascore/ibc/src/test/java/ibc/ics25/handler/IBCHandlerTest.java
```bash
feat: save write ack event height
```
```bash
```
> feat: save write ack event height

- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/fee.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/ibc_host.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/send_message.rs
Do not send fund to IBC host on send_call_message
```bash
fix: do not send fund to ibc core on send_call_message
```
```bash
```
> fix: do not send fund to ibc core on send_call_message

- README.md
- docs/ibc-setup-using-dive-cli.md
```bash
docs: add IBC setup using DIVE CLI to readme
```
> docs: add IBC setup using DIVE CLI to readme

- .github/workflows/basic-rust.yml
- .github/workflows/cosmwasm-contracts-code-coverage.yml
> ci: fix rustc version to 1.69.0

- Cargo.lock
- Cargo.toml
- contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/receive_packet.rs
- contracts/cosmwasm-vm/cw-ibc-core/tests/channel/test_receive_packet.rs
- contracts/cosmwasm-vm/cw-mock-ibc-connection/src/send_message.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
- contracts/cosmwasm-vm/cw-xcall-ibc-connection/tests/test_owner.rs
```bash
fix: error on duplicate packet
```
```bash
```
> fix: error on duplicate packet

- contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/LightClientTest.java
- contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/LightClientTestBase.java
- contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/data/validator-with-long-voting-power/commit.1.json
- contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/data/validator-with-long-voting-power/commit.2.json
- contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/data/validator-with-long-voting-power/commit.3.json
- contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/data/validator-with-long-voting-power/validators.1.json
- contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/data/validator-with-long-voting-power/validators.2.json
- contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/data/validator-with-long-voting-power/validators.3.json
- contracts/javascore/score-util/src/main/java/ibc/icon/score/util/Proto.java
Currently we use the size decoder to decode varints, but it is limited to ints. While varints can be as large as longs. So if to large values where supplied the decoding failed
```bash
```
```bash
```
> fix: Add seperate varint decoder which handles long values

- docs/e2e-integration-test-setup.md
```bash
fix: changed config env variable to TEST_CONFIG_PATH to match implementation
```
```bash
```
> fix: changed config env variable to TEST_CONFIG_PATH to match implementation

- contracts/javascore/ibc/src/main/java/ibc/ics04/channel/IBCPacket.java
- contracts/javascore/lightclients/ics-08-tendermint/src/main/java/ibc/ics08/tendermint/ICS08TendermintLightClient.java
- contracts/javascore/lightclients/ics-08-tendermint/src/main/java/ibc/ics08/tendermint/Tendermint.java
- contracts/javascore/lightclients/ics-08-tendermint/src/test/java/ibc/ics08/tendermint/LightClientTest.java
- contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/Tendermint.java
- contracts/javascore/lightclients/tendermint/src/main/java/ibc/tendermint/TendermintLightClient.java
- contracts/javascore/lightclients/tendermint/src/test/java/ibc/tendermint/LightClientTest.java
> feat: Apply code improvments suggested during audit

- .github/workflows/runner-start.yml
I noticed one of the CI workflows incorrectly references `machulav/ec2-github-runner`. GitHub requires a reference to use an action, so I added the V2 tag, and this should fix CI failures.
```bash
```
```bash
```
> fix: add reference to CI workflow to fix error

- contracts/cosmwasm-vm/cw-icon-light-client/src/contract.rs
- contracts/cosmwasm-vm/cw-icon-light-client/src/light_client.rs
- contracts/cosmwasm-vm/cw-icon-light-client/src/state.rs
changes made
- add test coverage for icon light client
> chore: add unit test coverage for icon light client

- contracts/javascore/ics20/src/main/java/ibc/ics20/ICS20Transfer.java
```bash
fix: address comparision in tokenFallback
```
```bash
```
> fix: address comparision in tokenFallback

- contracts/javascore/ics20/src/main/java/ibc/ics20/ICS20Transfer.java
- contracts/javascore/lightclients/ics-08-tendermint/src/main/java/ibc/ics08/tendermint/ICS08TendermintLightClient.java
> fix: javascore audit issues

- .github/workflows/java-contracts-test.yml
- contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/timeout_on_close.rs
- contracts/javascore/ibc/src/main/java/ibc/ics25/handler/IBCHandlerPacket.java
> fix: fix reentrancy

- .github/deployer/init_script.sh
- .github/workflows/run-deployer.yml
> ci: update repo url in deployment script

- .github/deployer/ec2_deployer.tf
- .github/deployer/init_script.sh
> ci: fix error on binary installation in deployment script

- .github/deployer/init_script.sh
- .github/deployer/sui_import.sh
> ci: add sui key import script
